/* GENERATED by scripts/generate-kitchen-sink.mjs — do not edit. 54 shadcn/ui registry examples. */
"use client";

import { Section } from "@/components/site/styleguide/Section";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import AccordionExample from "@/components/styleguide/examples/accordion-example";
import AlertDialogExample from "@/components/styleguide/examples/alert-dialog-example";
import AlertExample from "@/components/styleguide/examples/alert-example";
import AspectRatioExample from "@/components/styleguide/examples/aspect-ratio-example";
import AvatarExample from "@/components/styleguide/examples/avatar-example";
import BadgeExample from "@/components/styleguide/examples/badge-example";
import BreadcrumbExample from "@/components/styleguide/examples/breadcrumb-example";
import ButtonExample from "@/components/styleguide/examples/button-example";
import ButtonGroupExample from "@/components/styleguide/examples/button-group-example";
import CalendarExample from "@/components/styleguide/examples/calendar-example";
import CardExample from "@/components/styleguide/examples/card-example";
import CarouselExample from "@/components/styleguide/examples/carousel-example";
import ChartExample from "@/components/styleguide/examples/chart-example";
import CheckboxExample from "@/components/styleguide/examples/checkbox-example";
import CollapsibleExample from "@/components/styleguide/examples/collapsible-example";
import ComboboxExample from "@/components/styleguide/examples/combobox-example";
import CommandExample from "@/components/styleguide/examples/command-example";
import ContextMenuExample from "@/components/styleguide/examples/context-menu-example";
import DialogExample from "@/components/styleguide/examples/dialog-example";
import DrawerExample from "@/components/styleguide/examples/drawer-example";
import DropdownMenuExample from "@/components/styleguide/examples/dropdown-menu-example";
import EmptyExample from "@/components/styleguide/examples/empty-example";
import FieldExample from "@/components/styleguide/examples/field-example";
import HoverCardExample from "@/components/styleguide/examples/hover-card-example";
import InputExample from "@/components/styleguide/examples/input-example";
import InputGroupExample from "@/components/styleguide/examples/input-group-example";
import InputOtpExample from "@/components/styleguide/examples/input-otp-example";
import ItemExample from "@/components/styleguide/examples/item-example";
import KbdExample from "@/components/styleguide/examples/kbd-example";
import LabelExample from "@/components/styleguide/examples/label-example";
import MenubarExample from "@/components/styleguide/examples/menubar-example";
import NativeSelectExample from "@/components/styleguide/examples/native-select-example";
import NavigationMenuExample from "@/components/styleguide/examples/navigation-menu-example";
import PaginationExample from "@/components/styleguide/examples/pagination-example";
import PopoverExample from "@/components/styleguide/examples/popover-example";
import ProgressExample from "@/components/styleguide/examples/progress-example";
import RadioGroupExample from "@/components/styleguide/examples/radio-group-example";
import ResizableExample from "@/components/styleguide/examples/resizable-example";
import ScrollAreaExample from "@/components/styleguide/examples/scroll-area-example";
import SelectExample from "@/components/styleguide/examples/select-example";
import SeparatorExample from "@/components/styleguide/examples/separator-example";
import SheetExample from "@/components/styleguide/examples/sheet-example";
import SidebarExample from "@/components/styleguide/examples/sidebar-example";
import SkeletonExample from "@/components/styleguide/examples/skeleton-example";
import SliderExample from "@/components/styleguide/examples/slider-example";
import SonnerExample from "@/components/styleguide/examples/sonner-example";
import SpinnerExample from "@/components/styleguide/examples/spinner-example";
import SwitchExample from "@/components/styleguide/examples/switch-example";
import TableExample from "@/components/styleguide/examples/table-example";
import TabsExample from "@/components/styleguide/examples/tabs-example";
import TextareaExample from "@/components/styleguide/examples/textarea-example";
import ToggleExample from "@/components/styleguide/examples/toggle-example";
import ToggleGroupExample from "@/components/styleguide/examples/toggle-group-example";
import TooltipExample from "@/components/styleguide/examples/tooltip-example";

/* Providers the registry examples expect at the app root (tooltips, toasts). */
export function KitchenSink() {
  return (
    <TooltipProvider>
      {/* data-shadcn-scope: app/styleguide/styleguide.css restores shadcn's muted/accent semantics here;
          data-kitchen-sink: the axe gate tracks these vendored examples as a ratcheting baseline. */}
      <div data-shadcn-scope data-kitchen-sink>
        <h2 className="mb-10 mt-20 font-display text-3xl font-normal uppercase text-ink">
          Form controls
        </h2>
        <Section id="button" title="Button">
          <ButtonExample />
        </Section>
        <Section id="button-group" title="Button group">
          <ButtonGroupExample />
        </Section>
        <Section id="badge" title="Badge">
          <BadgeExample />
        </Section>
        <Section id="label" title="Label">
          <LabelExample />
        </Section>
        <Section id="input" title="Input">
          <InputExample />
        </Section>
        <Section id="input-group" title="Input group">
          <InputGroupExample />
        </Section>
        <Section id="input-otp" title="Input otp">
          <InputOtpExample />
        </Section>
        <Section id="textarea" title="Textarea">
          <TextareaExample />
        </Section>
        <Section id="native-select" title="Native select">
          <NativeSelectExample />
        </Section>
        <Section id="select" title="Select">
          <SelectExample />
        </Section>
        <Section id="checkbox" title="Checkbox">
          <CheckboxExample />
        </Section>
        <Section id="radio-group" title="Radio group">
          <RadioGroupExample />
        </Section>
        <Section id="switch" title="Switch">
          <SwitchExample />
        </Section>
        <Section id="slider" title="Slider">
          <SliderExample />
        </Section>
        <Section id="toggle" title="Toggle">
          <ToggleExample />
        </Section>
        <Section id="toggle-group" title="Toggle group">
          <ToggleGroupExample />
        </Section>
        <Section id="field" title="Field">
          <FieldExample />
        </Section>
        <Section id="combobox" title="Combobox">
          <ComboboxExample />
        </Section>
        <Section id="calendar" title="Calendar">
          <CalendarExample />
        </Section>
        <h2 className="mb-10 mt-20 font-display text-3xl font-normal uppercase text-ink">
          Layout & feedback
        </h2>
        <Section id="card" title="Card">
          <CardExample />
        </Section>
        <Section id="separator" title="Separator">
          <SeparatorExample />
        </Section>
        <Section id="alert" title="Alert">
          <AlertExample />
        </Section>
        <Section id="aspect-ratio" title="Aspect ratio">
          <AspectRatioExample />
        </Section>
        <Section id="avatar" title="Avatar">
          <AvatarExample />
        </Section>
        <Section id="breadcrumb" title="Breadcrumb">
          <BreadcrumbExample />
        </Section>
        <Section id="kbd" title="Kbd">
          <KbdExample />
        </Section>
        <Section id="pagination" title="Pagination">
          <PaginationExample />
        </Section>
        <Section id="progress" title="Progress">
          <ProgressExample />
        </Section>
        <Section id="skeleton" title="Skeleton">
          <SkeletonExample />
        </Section>
        <Section id="spinner" title="Spinner">
          <SpinnerExample />
        </Section>
        <Section id="empty" title="Empty">
          <EmptyExample />
        </Section>
        <Section id="item" title="Item">
          <ItemExample />
        </Section>
        <Section id="scroll-area" title="Scroll area">
          <ScrollAreaExample />
        </Section>
        <Section id="resizable" title="Resizable">
          <ResizableExample />
        </Section>
        <Section id="sonner" title="Sonner">
          <SonnerExample />
        </Section>
        <h2 className="mb-10 mt-20 font-display text-3xl font-normal uppercase text-ink">
          Overlays & navigation
        </h2>
        <Section id="accordion" title="Accordion">
          <AccordionExample />
        </Section>
        <Section id="alert-dialog" title="Alert dialog">
          <AlertDialogExample />
        </Section>
        <Section id="collapsible" title="Collapsible">
          <CollapsibleExample />
        </Section>
        <Section id="context-menu" title="Context menu">
          <ContextMenuExample />
        </Section>
        <Section id="dialog" title="Dialog">
          <DialogExample />
        </Section>
        <Section id="drawer" title="Drawer">
          <DrawerExample />
        </Section>
        <Section id="dropdown-menu" title="Dropdown menu">
          <DropdownMenuExample />
        </Section>
        <Section id="hover-card" title="Hover card">
          <HoverCardExample />
        </Section>
        <Section id="menubar" title="Menubar">
          <MenubarExample />
        </Section>
        <Section id="navigation-menu" title="Navigation menu">
          <NavigationMenuExample />
        </Section>
        <Section id="popover" title="Popover">
          <PopoverExample />
        </Section>
        <Section id="sheet" title="Sheet">
          <SheetExample />
        </Section>
        <Section id="sidebar" title="Sidebar">
          <SidebarExample />
        </Section>
        <Section id="tabs" title="Tabs">
          <TabsExample />
        </Section>
        <Section id="tooltip" title="Tooltip">
          <TooltipExample />
        </Section>
        <Section id="command" title="Command">
          <CommandExample />
        </Section>
        <h2 className="mb-10 mt-20 font-display text-3xl font-normal uppercase text-ink">
          Data & complex
        </h2>
        <Section id="table" title="Table">
          <TableExample />
        </Section>
        <Section id="carousel" title="Carousel">
          <CarouselExample />
        </Section>
        <Section id="chart" title="Chart">
          <ChartExample />
        </Section>
      </div>
      <Toaster />
    </TooltipProvider>
  );
}
